;
; File generated by cc65 v 2.18 - Git 4a22487
;
	.fopt		compiler,"cc65 v 2.18 - Git 4a22487"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "m01.c", 678, 1590957733
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stdio.h", 6189, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stddef.h", 3057, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stdarg.h", 2913, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stdlib.h", 5999, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stdint.h", 6196, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/c64.h", 6969, 1586648036
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/_vic2.h", 10835, 1586648036
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/_sid.h", 3626, 1586648035
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/_6526.h", 3962, 1586648035
	.forceimport	__STARTUP__
	.forceimport	initmainargs
	.export		_hmm
	.export		_main

; ---------------------------------------------------------------
; void __near__ hmm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hmm: near

	.dbg	func, "hmm", "00", extern, "_hmm"
	.dbg	sym, "scr", "00", auto, -2

.segment	"CODE"

;
; uint8_t *scr   = (uint8_t*) 0x0400;  // screen
;
	.dbg	line, "m01.c", 11
	ldx     #$04
	lda     #$00
	jsr     pushax
;
; *(scr + 40 * 0 ) = 0;
;
	.dbg	line, "m01.c", 12
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	tya
	sta     (ptr1),y
;
; }
;
	.dbg	line, "m01.c", 13
	jmp     incsp2
	.dbg	line

.endproc

; ---------------------------------------------------------------
; int __near__ __cdecl__ main (int, __near__ unsigned char * *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"
	.dbg	sym, "argc", "00", auto, 2
	.dbg	sym, "argv", "00", auto, 0
	.dbg	sym, "chars", "00", auto, -2
	.dbg	sym, "scr", "00", auto, -4

.segment	"CODE"

;
; unsigned char *chars = (uint8_t*) 0x2000;  // char memory
;
	.dbg	line, "m01.c", 17
	ldx     #$20
	lda     #$00
	jsr     pushax
;
; uint8_t       *scr   = (uint8_t*) 0x0400;  // screen
;
	.dbg	line, "m01.c", 18
	ldx     #$04
	jsr     pushax
;
; VIC.bgcolor[0] = 1;
;
	.dbg	line, "m01.c", 21
	lda     #$01
	sta     $D021
;
; VIC.bgcolor[21] = 5;
;
	.dbg	line, "m01.c", 22
	lda     #$05
	sta     $D036
;
; VIC.bgcolor[2] = 14;
;
	.dbg	line, "m01.c", 23
	lda     #$0E
	sta     $D023
;
; VIC.bgcolor[3] = 8;
;
	.dbg	line, "m01.c", 24
	lda     #$08
	sta     $D024
;
; *( chars + 0 ) = 0;
;
	.dbg	line, "m01.c", 29
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$00
	tay
L0029:	sta     (ptr1),y
;
; COLOR_RAM[ 40*0 + 0 ] = 0;
;
	.dbg	line, "m01.c", 33
	ldx     #$D8
	sta     ptr1
	stx     ptr1+1
;
; while(1)
;
	.dbg	line, "m01.c", 31
	jmp     L0029
	.dbg	line

.endproc

