;
; File generated by cc65 v 2.18 - Git 4a22487
;
	.fopt		compiler,"cc65 v 2.18 - Git 4a22487"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "m02.c", 2805, 1591244331
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stdio.h", 6189, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stddef.h", 3057, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stdarg.h", 2913, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stdlib.h", 5999, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/stdint.h", 6196, 1586648038
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/c64.h", 6969, 1586648036
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/_vic2.h", 10835, 1586648036
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/_sid.h", 3626, 1586648035
	.dbg		file, "C:\Users\Noah\fun\c64\cc65\include/_6526.h", 3962, 1586648035
	.forceimport	__STARTUP__
	.export		_main
	.export		_hmm

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"
	.dbg	sym, "demo_main", "00", auto, -2
	.dbg	sym, "mandala_draw", "00", auto, -4
	.dbg	sym, "hires_clear", "00", auto, -6
	.dbg	sym, "scrn_clr", "00", auto, -8
	.dbg	sym, "mandala_base", "00", auto, -10
	.dbg	sym, "angle_bump", "00", auto, -12
	.dbg	sym, "points_count", "00", auto, -14
	.dbg	sym, "iters_count", "00", auto, -16
	.dbg	sym, "scrn_clr_color", "00", auto, -18
	.dbg	sym, "scrn_clr_byte", "00", auto, -20
	.dbg	sym, "plot_color", "00", auto, -22
	.dbg	sym, "angle", "00", auto, -24
	.dbg	sym, "angle_delta", "00", auto, -26
	.dbg	sym, "radius", "00", auto, -28
	.dbg	sym, "radius_delta", "00", auto, -30
	.dbg	sym, "angle_ratchet", "00", auto, -32
	.dbg	sym, "radius_ratchet", "00", auto, -34
	.dbg	sym, "angle_delta2", "00", auto, -36
	.dbg	sym, "radius_delta2", "00", auto, -38

.segment	"CODE"

;
; uint8_t *mandala_base = (uint8_t*)0x5900;  // mandala_base
;
	.dbg	line, "m02.c", 17
	jsr     decsp8
	ldx     #$59
	lda     #$00
	jsr     pushax
;
; uint8_t *angle_bump     = mandala_base + 3;
;
	.dbg	line, "m02.c", 18
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L0008
	inx
L0008:	jsr     pushax
;
; uint8_t *points_count   = mandala_base + 4;
;
	.dbg	line, "m02.c", 19
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$04
	bcc     L000A
	inx
L000A:	jsr     pushax
;
; uint8_t *iters_count    = mandala_base + 6;
;
	.dbg	line, "m02.c", 20
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$06
	bcc     L000C
	inx
L000C:	jsr     pushax
;
; uint8_t *scrn_clr_color = mandala_base + 8;
;
	.dbg	line, "m02.c", 21
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$08
	bcc     L000E
	inx
L000E:	jsr     pushax
;
; uint8_t *scrn_clr_byte  = mandala_base + 9;
;
	.dbg	line, "m02.c", 22
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$09
	bcc     L0010
	inx
L0010:	jsr     pushax
;
; uint8_t *plot_color     = mandala_base + 11;
;
	.dbg	line, "m02.c", 23
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$0B
	bcc     L0012
	inx
L0012:	jsr     pushax
;
; uint8_t *angle          = mandala_base + 12;
;
	.dbg	line, "m02.c", 24
	ldy     #$0D
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$0C
	bcc     L0014
	inx
L0014:	jsr     pushax
;
; uint8_t *angle_delta    = mandala_base + 14;
;
	.dbg	line, "m02.c", 25
	ldy     #$0F
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$0E
	bcc     L0016
	inx
L0016:	jsr     pushax
;
; uint8_t *radius         = mandala_base + 16;
;
	.dbg	line, "m02.c", 26
	ldy     #$11
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$10
	bcc     L0018
	inx
L0018:	jsr     pushax
;
; uint8_t *radius_delta   = mandala_base + 18;
;
	.dbg	line, "m02.c", 27
	ldy     #$13
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$12
	bcc     L001A
	inx
L001A:	jsr     pushax
;
; uint8_t *angle_ratchet  = mandala_base + 20;
;
	.dbg	line, "m02.c", 28
	ldy     #$15
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$14
	bcc     L001C
	inx
L001C:	jsr     pushax
;
; uint8_t *radius_ratchet = mandala_base + 21;
;
	.dbg	line, "m02.c", 29
	ldy     #$17
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$15
	bcc     L001E
	inx
L001E:	jsr     pushax
;
; uint8_t *angle_delta2   = mandala_base + 22;
;
	.dbg	line, "m02.c", 30
	ldy     #$19
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$16
	bcc     L0020
	inx
L0020:	jsr     pushax
;
; uint8_t *radius_delta2  = mandala_base + 23;
;
	.dbg	line, "m02.c", 31
	ldy     #$1B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$17
	bcc     L0022
	inx
L0022:	jsr     pushax
;
; demo_main    = (void*)0xc000;
;
	.dbg	line, "m02.c", 33
	ldy     #$24
	lda     #$00
	sta     (sp),y
	lda     #$C0
	iny
	sta     (sp),y
;
; mandala_draw = (void*)0x5920;
;
	.dbg	line, "m02.c", 34
	ldy     #$22
	lda     #$20
	sta     (sp),y
	lda     #$59
	iny
	sta     (sp),y
;
; hires_clear  = (void*)0x5018;
;
	.dbg	line, "m02.c", 35
	ldy     #$20
	lda     #$18
	sta     (sp),y
	lda     #$50
	iny
	sta     (sp),y
;
; scrn_clr     = (void*)0x5020;
;
	.dbg	line, "m02.c", 36
	ldy     #$1E
	lda     #$20
	sta     (sp),y
	lda     #$50
	iny
	sta     (sp),y
;
; *scrn_clr_color   = 0x10;  // upper nybble is set color, up = set
;
	.dbg	line, "m02.c", 38
	ldy     #$15
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$10
	ldy     #$00
	sta     (ptr1),y
;
; *scrn_clr_byte    = 0x0f;  // lower nybble is color & val?
;
	.dbg	line, "m02.c", 39
	ldy     #$13
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$0F
	ldy     #$00
	sta     (ptr1),y
;
; *plot_color       = 2;
;
	.dbg	line, "m02.c", 40
	ldy     #$11
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$02
	ldy     #$00
	sta     (ptr1),y
;
; *points_count     = 0;
;
	.dbg	line, "m02.c", 42
	ldy     #$19
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$00
	tay
	sta     (ptr1),y
;
; *(points_count+1) = 50;
;
	.dbg	line, "m02.c", 43
	ldy     #$19
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     #$32
	sta     (ptr1),y
;
; *iters_count      = 0;
;
	.dbg	line, "m02.c", 44
	ldy     #$17
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$00
	tay
	sta     (ptr1),y
;
; *(iters_count+1)  = 50;
;
	.dbg	line, "m02.c", 45
	ldy     #$17
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     #$32
	sta     (ptr1),y
;
; *angle            = 0;
;
	.dbg	line, "m02.c", 47
	ldy     #$0F
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$00
	tay
	sta     (ptr1),y
;
; *(angle+1)        = 0;
;
	.dbg	line, "m02.c", 48
	ldy     #$0F
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     #$00
	sta     (ptr1),y
;
; *radius           = 100;
;
	.dbg	line, "m02.c", 49
	ldy     #$0B
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$64
	ldy     #$00
	sta     (ptr1),y
;
; *(radius+1)       = 0;
;
	.dbg	line, "m02.c", 50
	ldy     #$0B
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     #$00
	sta     (ptr1),y
;
; *angle_delta      = 1;
;
	.dbg	line, "m02.c", 52
	ldy     #$0D
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$01
	ldy     #$00
	sta     (ptr1),y
;
; *(angle_delta+1)  = 0;
;
	.dbg	line, "m02.c", 53
	ldy     #$0D
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     #$00
	sta     (ptr1),y
;
; *radius_delta     = 1;  // per point
;
	.dbg	line, "m02.c", 54
	ldy     #$09
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$01
	ldy     #$00
	sta     (ptr1),y
;
; *(radius_delta+1) = 1;
;
	.dbg	line, "m02.c", 55
	ldy     #$09
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	tya
	sta     (ptr1),y
;
; *angle_ratchet    = 0;
;
	.dbg	line, "m02.c", 57
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$00
	tay
	sta     (ptr1),y
;
; *radius_ratchet   = 5;  // draw the next ones wit this delta
;
	.dbg	line, "m02.c", 58
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$05
	ldy     #$00
	sta     (ptr1),y
;
; *angle_delta2      = 0;
;
	.dbg	line, "m02.c", 60
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$00
	tay
	sta     (ptr1),y
;
; *(angle_delta2+1)  = 0;
;
	.dbg	line, "m02.c", 61
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
	lda     #$00
	sta     (ptr1),y
;
; *radius_delta2     = 0;
;
	.dbg	line, "m02.c", 62
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	tya
	sta     (ptr1),y
;
; *(radius_delta2+1) = 0;
;
	.dbg	line, "m02.c", 63
	iny
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	iny
	lda     #$00
	sta     (ptr1),y
;
; *angle_bump        = 1;  // adds at end of each iteration
;
	.dbg	line, "m02.c", 65
	ldy     #$1B
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$01
	ldy     #$00
	sta     (ptr1),y
;
; (*scrn_clr)();    // text screen, uses scrn_clr_col?
;
	.dbg	line, "m02.c", 67
	ldy     #$1F
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     callax
;
; (*hires_clear)(); // hires screen, uses scrn_clr_byte?
;
	.dbg	line, "m02.c", 68
	ldy     #$21
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     callax
;
; (*demo_main)();   // multiply init, hires_start
;
	.dbg	line, "m02.c", 69
	ldy     #$25
L0093:	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     callax
;
; *angle = 25;
;
	.dbg	line, "m02.c", 74
	ldy     #$0F
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$19
	ldy     #$00
	sta     (ptr1),y
;
; *radius = 150;
;
	.dbg	line, "m02.c", 75
	ldy     #$0B
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$96
	ldy     #$00
	sta     (ptr1),y
;
; (*mandala_draw)();
;
	.dbg	line, "m02.c", 83
	ldy     #$23
;
; while( 1 )
;
	.dbg	line, "m02.c", 72
	jmp     L0093
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void __near__ hmm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hmm: near

	.dbg	func, "hmm", "00", extern, "_hmm"
	.dbg	sym, "scr", "00", auto, -2

.segment	"CODE"

;
; uint8_t       *scr   = (uint8_t*) 0x0400;  // screen
;
	.dbg	line, "m02.c", 95
	ldx     #$04
	lda     #$00
	jsr     pushax
;
; VIC.bgcolor[0] = 1;
;
	.dbg	line, "m02.c", 98
	lda     #$01
	sta     $D021
;
; VIC.bgcolor[21] = 5;
;
	.dbg	line, "m02.c", 99
	lda     #$05
	sta     $D036
;
; VIC.bgcolor[2] = 14;
;
	.dbg	line, "m02.c", 100
	lda     #$0E
	sta     $D023
;
; VIC.bgcolor[3] = 8;
;
	.dbg	line, "m02.c", 101
	lda     #$08
	sta     $D024
;
; COLOR_RAM[ 40*0 + 0 ] = 0;
;
	.dbg	line, "m02.c", 110
	ldx     #$D8
	lda     #$00
L0095:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	sta     (ptr1),y
;
; while(1)
;
	.dbg	line, "m02.c", 108
	jmp     L0095
	.dbg	line

.endproc

